version: '1.0'
displayName: 易班自动签到

stages:
  - name: signin
    steps:
      - name: run-signin
        script:
          - python -m pip install --upgrade pip
          - pip install -r requirements.txt
          - python scripts/signin.py
